spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.context: DEBUG
    org.springframework.beans: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.boot.autoconfigure: TRACE
