spring:
  application:
    name: user-service

  # Локальный fallback для Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml

  config:
    import: optional:configserver:http://localhost:8888

  main:
    log-startup-info: true
    debug: true

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

      # КРИТИЧЕСКОЕ — разрешает внешнему YAML перезаписывать локальный
      allow-override: true
      override-none: true

logging:
  level:
    liquibase: DEBUG
    liquibase.changelog: DEBUG
    liquibase.parser: DEBUG
    liquibase.integration: DEBUG
    liquibase.executor: DEBUG
    liquibase.database: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.servicelocator: DEBUG

    # Логи загрузки конфигов — покажут, применяется ли внешний YAML
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.core.io: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
