server:
  port: 8083   # порт для cart-service

spring:
  application:
    name: cart-service

  redis:
    host: localhost
    port: 6379

# Если используешь Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"