server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0

        - id: product-service-internal
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/internal/products/**
          filters:
            - StripPrefix=0

        - id: product-service-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - StripPrefix=0