server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: none         #jdbc:postgresql://postgres:5432/orderdb
    username: user
    password: password

  jpa:
    enabled: false

    hibernate:
      ddl-auto: update
    show-sql: true
