server:
  port: 8085

spring:
  application:
    name: order-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      label: main
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

  datasource:
    url: jdbc:postgresql://localhost:5432/hardwarestore?currentSchema=order_service
    username: postgres
    password: orion
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml
    default-schema: order_service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
