server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hardwarestore?currentSchema=payment_service
    username: postgres
    password: orion
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml

  logging:
    level:
      liquibase: DEBUG
      liquibase.changelog: DEBUG
      liquibase.parser: DEBUG
      liquibase.integration: DEBUG
      liquibase.executor: DEBUG
      liquibase.database: DEBUG
      liquibase.lockservice: DEBUG
      liquibase.servicelocator: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

debug: true