server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hardwarestore?currentSchema=payment_service
    username: postgres
    password: orion
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml
    default-schema: payment_service

  logging:
    level:
      liquibase: DEBUG
      liquibase.changelog: DEBUG
      liquibase.parser: DEBUG
      liquibase.integration: DEBUG
      liquibase.executor: DEBUG
      liquibase.database: DEBUG
      liquibase.lockservice: DEBUG
      liquibase.servicelocator: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service   # уникальный для каждого сервиса
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hardwarestore.common.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

debug: true