server:
  port: 8300   # порт для saga-coordinator

spring:
  application:
    name: saga-coordinator

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: saga-coordinator
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hardwarestore.common.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  admin:
    auto-create: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

debug: true
